spring:
  #引入外部文件
  profiles:
    # 数据库配置
    # type: com.alibaba.druid.pool.DruidDataSource
    active: druid
  output:
    ansi:
      enabled: detect
  #静态资源配置
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:templates,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  redis:
    database: 0
    password: zyWxznV
    host: 47.103.215.103
    port: 6379
    pool:
      max-active: 300
      max-wait: 3000
      max-idle: 4000
      min-idle: 100
    timeout: 5000
  cache:
    type: redis
  jpa:
    open-in-view: false

server:
  port: 8080


redis.expireTime: 3600







mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false