spring:
  #引入外部文件
  profiles:
    include: druid
  # 数据库配置
    # type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/film?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&useSSL=true
#    username: root
#    password: 285413
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: detect

  #模板引擎
  thymeleaf:
    #模板缓存
    cache: false
    enabled: true
  #静态资源配置
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:templates,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  redis:
    database: 0
#    password: 285413
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: 3000
      max-idle: 4000
      min-idle: 0
    timeout: 5000


#mybatis配置
  #配置实体类映射和mappeclasspath:r.xml文件路径
mybatis:
  type-aliases-package: com.bowensun.film.domain
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080







