spring:
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/film?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&useSSL=true&serverTimezone=UTC
      username: root
      password: 285413
      #driver-class-name: oracle.jdbc.OracleDriver
      driver-class-name: com.mysql.cj.jdbc.Driver
      #初始化时建立物理连接的个数
      initial-size: 10
      #最大连接数量
      max-active: 100
      #最小连接数量
      min-idle: 5
      #最大等待时间（毫秒）
      max-wait: 60000
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
      pool-prepared-statements: true
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: 100
      #用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用
      validation-query: select 'x'
      #检测连接是否有效的超时时间
      validation-query-timeout: 1
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      #有两个含义：
             #1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
             #2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      time-between-eviction-runs-millis: 5


    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=false;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
  #  druidLoginName: root # 登录druid的账号
  #  druidPassword: 285413 # 登录druid的密码
    # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      #是否启用StatFilter默认值false
#      web-stat-filter.enabled: true
#      web-stat-filter.url-pattern:
#      web-stat-filter.exclusions:
#      web-stat-filter.session-stat-enable: true
#      web-stat-filter.session-stat-max-count: 1000
#      web-stat-filter.principal-session-name:
#      web-stat-filter.principal-cookie-name:
#      web-stat-filter.profile-enable:

      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置

      stat-view-servlet.enabled: true #是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
      stat-view-servlet.url-pattern: /druid/*
#      stat-view-servlet.reset-enable:
      #监控界面用户名
      stat-view-servlet.login-username: root
      #监控界面密码
      stat-view-servlet.login-password: 285413
      #白名单
#      stat-view-servlet.allow:
      #黑名单
#      stat-view-servlet.deny:

      # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
#      spring.datasource.druid.aop-patterns= # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
