spring:
  #引入外部文件
  profiles:
    active: druid
  output:
    ansi:
      enabled: detect
  #静态资源配置
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:templates,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  redis:
    database: 1
    password: zyWxznV
    host: 47.103.215.103
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 300
        max-wait: 3000
        max-idle: 4000
        min-idle: 100
  cache:
    type: redis
  jpa:
    open-in-view: false

server:
  port: 9090
  servlet:
    context-path: '/film'

redis:
  expireTime: 3600


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      # ignored: 忽略非空判断，所有字段都可以被更新为 null
      # not_null: 更新为 null 时忽略更新
      # not_empty: 字符串不能被更新为 null 或 空，其他类型不能被更新为 null
      update-strategy: ignored

#日志配置 无特殊需求无需更改
logging:
  config:  classpath:log4j2.xml
  level:
    root: INFO
    javax.activation: info
    org.apache.catalina: INFO
    org.apache.commons.beanutils.converters: INFO
    org.apache.coyote.http11.Http11Processor: INFO
    org.apache.http: INFO
    org.apache.tomcat: INFO
    org.springframework: INFO
    com.chinamobile.cmss.bdpaas.resource.monitor: DEBUG


############ 自定义配置 ##########

film:
  config:
    isAddressEnabled: true
  captcha:
    type: 'math'
  jwt:
    token:
      # 前缀
      prefix: 'Bearer'
      # 签发人
      issuer: 'bwensun'
      expiredTime: 30
      subject: 'film'
      audience: 'fans'
      secret: 'tingzheng'
      refreshInterval: 20
  async:
    corePoolSize: 5
    maxPoolSize: 20
    queueCapacity: 100
    keepAliveSecond: 300
    threadNamePrefix: async-