spring:
  #引入外部文件
  profiles:
    # 数据库配置
    # type: com.alibaba.druid.pool.DruidDataSource
    active: druid
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: detect

  #模板引擎
  thymeleaf:
    #模板缓存
    cache: false
    enabled: true
  #静态资源配置
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:templates,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  redis:
    database: 0
    password: zyWxznV
    host: 47.103.215.103
    port: 6379
    pool:
      max-active: 300
      max-wait: 3000
      max-idle: 4000
      min-idle: 100
    timeout: 5000
  cache:
    type: redis

#mybatis配置
  #配置实体类映射和mappeclasspath:r.xml文件路径
mybatis:
  type-aliases-package: com.bowensun.film.domain
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080

#分页插件配置


redis.expireTime: 3600








